name: Show Branch and Maven Version

on:
  push:
    branches:
      - '**'   # 所有分支都触发

jobs:
  show-info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'   # 你的项目用的JDK版本

      - name: Get Maven version
        id: get_version
        run: |
          VERSION=$(grep -m 1 '<version>' pom.xml | sed 's/.*<version>\(.*\)<\/version>.*/\1/')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Show branch and version
        run: |
          echo "Branch name: ${{ github.ref_name }}"
          echo "Project version: ${{ env.VERSION }}"

      - name: token
        run: |
          echo "jenkins user: ${{ secrets.JENKINS_USER }}"
          echo "jenkins token: ${{ secrets.JENKINS_TOKEN }}"